export const REMOTE_EXPERT_ERROR_CODES = [
  "ACP_CONTRACT_LOCK_MISSING",
  "ACP_CONTRACT_INCOMPATIBLE",
  "ACP_ADAPTER_VERSION_UNREADABLE",
  "ACP_BINARY_MISSING",
  "ACP_BINARY_INTEGRITY_FAILED",
  "ACP_BINARY_UNSUPPORTED",
  "ACP_PROCESS_START_FAILED",
  "ACP_PROCESS_CRASHED",
  "ACP_INITIALIZE_TIMEOUT",
  "ACP_PROMPT_REJECTED",
  "ACP_PROTOCOL_ERROR",
  "ACP_OUTCOME_UNKNOWN",
  "ACP_SESSION_RESUME_FORBIDDEN",
  "ACP_SESSION_NOT_FOUND",
  "ACP_SESSION_PROFILE_MISMATCH",
  "ACP_SESSION_TEMPORARILY_UNAVAILABLE",
  "ACP_SESSION_BUSY",
  "ACP_PERMISSION_ALREADY_RESOLVED",
  "ACP_PERMISSION_RESPONSE_FAILED",
  "ACP_CANCEL_FAILED",
  "ACP_CANCEL_GRACE_EXCEEDED",
  "ACP_CLOSE_FAILED",
  "REMOTE_BINDING_CONFLICT",
  "REMOTE_BINDING_NOT_FOUND",
  "REMOTE_METADATA_MIGRATION_FAILED",
  "REMOTE_EXPERT_CATALOG_AUTH",
  "REMOTE_EXPERT_CATALOG_UNAVAILABLE",
  "REMOTE_EXPERT_SCHEMA_INVALID",
  "REMOTE_IPC_INVALID_INPUT",
  "REMOTE_IPC_NOT_READY",
  "REMOTE_ATTACHMENT_UPLOAD_FAILED",
  "REMOTE_ATTACHMENT_PROOF_FAILED",
  "REMOTE_ARTIFACT_URI_INVALID",
  "REMOTE_ARTIFACT_DOWNLOAD_FAILED",
  "REMOTE_ARTIFACT_INTEGRITY_FAILED",
  "REMOTE_TRANSCRIPT_PERSIST_FAILED",
  "REMOTE_AUTH_REQUIRED",
  "REMOTE_AUTH_REFRESH_FAILED",
  "REMOTE_EXPERT_PRODUCTION_GATE_BLOCKED",
  "REMOTE_PROFILE_INVALID",
  "REMOTE_PROFILE_IMMUTABLE",
  "REMOTE_TURN_CONFLICT",
] as const;

export type RemoteExpertErrorCode = (typeof REMOTE_EXPERT_ERROR_CODES)[number];

export function isRemoteExpertErrorCode(
  value: unknown,
): value is RemoteExpertErrorCode {
  return (
    typeof value === "string" &&
    (REMOTE_EXPERT_ERROR_CODES as readonly string[]).includes(value)
  );
}

export class RemoteExpertError extends Error {
  readonly code: RemoteExpertErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(
    code: RemoteExpertErrorCode | string,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "RemoteExpertError";
    this.code = isRemoteExpertErrorCode(code) ? code : "ACP_PROTOCOL_ERROR";
    this.details = details;
  }
}
