import { writeFileSync, existsSync, readFileSync } from "fs";
import { getAiOsPaths } from "./aios-paths";
import { getRuntimeSetting, setRuntimeSetting } from "../profile-runtime-db";
import { resolveAiosBackendUrl } from "./aios-home-url";
import { normalizeBackendBaseUrl } from "../../shared/auth/auth-url";

export interface AiOsEnvConfig {
  backendPort: number;
  frontendPort: number;
  databaseUrl: string;
  hermesGatewayUrl: string;
  hermesGatewayToken: string;
  hermesWebuiUrl: string;
}

const DEFAULT_BACKEND_PORT = 8000;
const DEFAULT_FRONTEND_PORT = 3000;
const DEFAULT_DATABASE_URL = "postgresql://postgres:postgres@127.0.0.1:55432/portal";
const DEFAULT_HERMES_GATEWAY_URL = "http://127.0.0.1:8642";
const DEFAULT_HERMES_WEBUI_URL = "http://127.0.0.1:8787";

export function getAiOsEnvConfig(): AiOsEnvConfig {
  const stored = getRuntimeSetting("aios-env-config");
  if (stored) {
    try {
      return JSON.parse(stored) as AiOsEnvConfig;
    } catch { /* use defaults */ }
  }
  return {
    backendPort: DEFAULT_BACKEND_PORT,
    frontendPort: DEFAULT_FRONTEND_PORT,
    databaseUrl: DEFAULT_DATABASE_URL,
    hermesGatewayUrl: DEFAULT_HERMES_GATEWAY_URL,
    hermesGatewayToken: "",
    hermesWebuiUrl: DEFAULT_HERMES_WEBUI_URL,
  };
}

export function saveAiOsEnvConfig(config: Partial<AiOsEnvConfig>): void {
  const current = getAiOsEnvConfig();
  const merged = { ...current, ...config };
  setRuntimeSetting("aios-env-config", JSON.stringify(merged));
}

export function writeAiOsEnvFile(): string {
  const paths = getAiOsPaths();
  const config = getAiOsEnvConfig();
  const remoteApiBase = `${normalizeBackendBaseUrl(resolveAiosBackendUrl())}/api/v1`;
  let gatewayToken = "";
  const localToken = getRuntimeSetting("aios-local-token");
  if (localToken) {
    try {
      gatewayToken = JSON.parse(localToken) as string;
    } catch {
      gatewayToken = localToken;
    }
  }

  const lines = [
    "# Generated by Hermes Desktop — do not edit manually",
    "",
    "# Portal Frontend (local process; API points to remote backend)",
    `NEXT_PUBLIC_SITE_URL=http://127.0.0.1:${config.frontendPort}`,
    `NEXT_PUBLIC_API_URL=${remoteApiBase}`,
    "",
    "# Hermes Gateway",
    `HERMES_GATEWAY_BASE_URL=${config.hermesGatewayUrl}`,
    ...(gatewayToken ? [`HERMES_GATEWAY_TOKEN=${gatewayToken}`] : []),
    "HERMES_GATEWAY_TIMEOUT_MS=10000",
    "",
    "# Hermes WebUI Runtime",
    `HERMES_WEBUI_BASE_URL=${config.hermesWebuiUrl}`,
    "",
  ];

  const content = lines.join("\n");
  writeFileSync(paths.envFilePath, content, "utf-8");
  return paths.envFilePath;
}

export function readAiOsEnvFile(): Record<string, string> {
  const paths = getAiOsPaths();
  if (!existsSync(paths.envFilePath)) return {};

  const content = readFileSync(paths.envFilePath, "utf-8");
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx > 0) {
      result[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
  }
  return result;
}
