export type WorkErrorCode =
  | "GATEWAY_OFFLINE"
  | "GATEWAY_UNHEALTHY"
  | "MCP_TOOLS_LIST_FAILED"
  | "MCP_TOOL_CALL_FAILED"
  | "MCP_INVALID_ARGUMENTS"
  | "MCP_APPROVAL_REQUIRED"
  | "MCP_GRANT_REVOKED"
  | "RUN_NOT_FOUND"
  | "RUN_TIMEOUT"
  | "ARTIFACT_NOT_FOUND"
  | "ARTIFACT_PREVIEW_FAILED"
  | "ARTIFACT_DOWNLOAD_FAILED"
  | "PERMISSION_DENIED"
  | "WORK_TASK_NOT_FOUND"
  | "WORK_STREAM_FAILED"
  | "WORK_STREAM_ABORTED"
  | "WORK_EVENT_PARSE_FAILED"
  | "WORK_EXPERT_NOT_FOUND"
  | "WORK_TEAM_NOT_FOUND"
  | "WORK_TOOL_FAILED"
  | "WORK_APPROVAL_REJECTED"
  | "WORK_OUTPUT_PREVIEW_FAILED"
  | "WORK_PERMISSION_DENIED"
  | "WORK_BACKEND_UNREACHABLE"
  | "UNKNOWN_ERROR";

export interface WorkError {
  code: WorkErrorCode;
  message: string;
  details?: string;
}
