/** v6.5 — GeneHub local error codes (PRD §11). */

export type GeneHubErrorCode =
  | "GENEHUB_NOT_AUTHENTICATED"
  | "GENEHUB_NOT_INITIALIZED"
  | "GENEHUB_API_FAILED"
  | "GENEHUB_BACKEND_URL_MISSING"
  | "GENEHUB_DESCRIPTOR_MISSING"
  | "GENEHUB_BACKEND_UNREACHABLE"
  | "GENEHUB_DEVICE_REGISTER_FAILED"
  | "GENEHUB_PROFILE_REGISTER_FAILED"
  | "GENEHUB_JOB_NOT_FOUND"
  | "GENEHUB_JOB_NOT_PENDING"
  | "GENEHUB_JOB_CLAIM_FAILED"
  | "GENEHUB_BUNDLE_DOWNLOAD_FAILED"
  | "GENEHUB_BUNDLE_INVALID"
  | "GENEHUB_SIGNATURE_INVALID"
  | "GENEHUB_HASH_MISMATCH"
  | "GENEHUB_UNSUPPORTED_RUNTIME"
  | "GENEHUB_INVALID_SKILL_NAME"
  | "GENEHUB_INVALID_FILE_PATH"
  | "GENEHUB_PATH_NOT_ALLOWED"
  | "GENEHUB_SYNC_INSTALLED_FAILED"
  | "HERMES_HOME_NOT_FOUND"
  | "HERMES_SKILL_WRITE_FAILED"
  | "HERMES_SCRIPT_WRITE_FAILED"
  | "HERMES_SNAPSHOT_CLEAN_FAILED"
  | "HERMES_RESTART_FAILED"
  | "HERMES_HEALTH_CHECK_FAILED"
  | "INSTALL_ROLLBACK_FAILED"
  | "INSTALL_PERMISSION_DENIED"
  | "GENEHUB_DISABLED"
  | "GENEHUB_PROFILE_MAPPING_MISSING"
  | "GENEHUB_SCRIPT_PROVENANCE_MISMATCH"
  | "GENEHUB_SCRIPT_OVERWRITE_BLOCKED";

export class GeneHubError extends Error {
  readonly code: GeneHubErrorCode;

  constructor(code: GeneHubErrorCode, message: string) {
    super(message);
    this.name = "GeneHubError";
    this.code = code;
  }
}

export function isGeneHubError(err: unknown): err is GeneHubError {
  return err instanceof GeneHubError;
}
